#!/usr/bin/env python3
"""Generate the P14 (E-null) configs: leave-one-out, held-out target.

Pre-registered in `PREDICTIONS.md` before this file was written. Reasoning in
`reports/reconsideration-consensus.md`.

**The one thing this experiment changes** is the object list. Everything else --
rotations, vote rule, model capacity, sensor noise -- is copied from the P7/P8
arms so that a difference cannot come from anywhere else.

Four configs:

  * `p14_pretrain9`   -- pretrain 5 LMs on NINE objects, `dice` held out
  * `p14_holdout_max`   -- eval on `dice` only, upstream vote
  * `p14_holdout_novote`-- eval on `dice` only, votes disabled
  * `p14_trained_max`   -- eval on a TRAINED object, the replication control

`dice` is the held-out object on purpose: P4's false-consensus episode was
`dice`, where five modules were independently correct and all five failed after
voting. The object that produced the effect is now the impossible one.

**Why the control matters more than the treatment.** If the 9-object
pretraining is silently broken, every module fails on everything, unanimity
could be anything, and the result would look like a finding. `p14_trained_max`
must reproduce known accuracy (~97% `any`) or the sweep is void.
"""
from __future__ import annotations

import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXP = os.path.join(HERE, "configs", "experiment")

# Upstream's 10. Verified 2026-08-20 against
# `upstream/.../env_interface/train_distinctobj_predefined.yaml` -- the train
# and eval lists are IDENTICAL, which is the fact this experiment exists to
# break.
ALL_OBJECTS = [
    "mug", "bowl", "potted_meat_can", "spoon", "strawberry",
    "mustard_bottle", "dice", "golf_ball", "c_lego_duplo", "banana",
]
HELD_OUT = "dice"
TRAINED = [o for o in ALL_OBJECTS if o != HELD_OUT]

# The control object. `mug` is trained, so accuracy on it must be normal.
CONTROL_OBJECT = "mug"

# Copied verbatim from the P7/P8 arms. Not re-derived: a rotation set that
# drifts from the earlier sweeps makes the replication control meaningless.
EVAL_ROTATIONS = [
    [35, 45, 0],
    [325, 45, 0],
    [35, 315, 0],
    [325, 315, 0],
]
PRETRAIN_ROTATIONS = [
    [0, 0, 0], [0, 90, 0], [0, 270, 0], [90, 0, 0], [90, 180, 0],
]


def yaml_list(items, indent):
    pad = " " * indent
    return "\n".join("%s- %s" % (pad, i) for i in items)


def rot_list(rots, indent):
    pad = " " * indent
    return "\n".join("%s- [%d, %d, %d]" % (pad, r[0], r[1], r[2]) for r in rots)


PRETRAIN = '''# @package _global_
# P14 (E-null) PRETRAINING -- NINE objects. `{held}` is held out.
#
# Generated by tools/make_p14_configs.py. Pre-registered in PREDICTIONS.md.
#
# This is the only pretraining in the project that does not cover the full
# object set, and that is the entire point: it creates the condition Nadi
# described -- a question whose correct answer is not among the alternatives.
#
# Identical to pb_pretrain_indomain.yaml except for the object list.
defaults:
  - /monty: graph_exp500_e3_t3_tot2500
  - /monty/motor_system_config: naive_scan_5
  - /monty/learning_module: displacement_5lm
  - /monty/sensor_module: 5sm_camera
  - /monty/connectivity: 5lm_5sm
  - /environment: mujoco_dist_agent_sensors5
  - /env_interface: train_distinctobj_predefined
  - /env_interface/positioning_procedures_train: getgoodview_viewfinder_patch0
  - /env_interface/transform: missing_depthto3d_sensor6
  - /logging: silent_info_train

experiment:
  _target_: tbp.monty.frameworks.experiments.pretraining_experiments.MontySupervisedObjectPretrainingExperiment
  config:
    show_sensor_output: false
    max_train_steps: 1000
    max_eval_steps: 500
    max_total_steps: 6000
    n_train_epochs: 5
    model_name_or_path: ''
    n_eval_epochs: 1
    match_criterion:
      _target_: tbp.monty.experiment.match_criteria.AnyLMsMatch
      count: 1
    seed: 42
    supervised_lm_ids: all
    train_env_interface_args:
      object_names:
{objects}
      object_init_sampler:
        rotations:
{rotations}
    logging:
      run_name: pb_holdout9_5lm
      output_dir: ${{path.expanduser:${{oc.env:MONTY_MODELS}}/polybrains}}
'''

EVAL = '''# @package _global_
# P14 (E-null) -- {title}
#
# Generated by tools/make_p14_configs.py. Pre-registered in PREDICTIONS.md.
#
# {why}
#
# Loads the NINE-object model `pb_holdout9_5lm`. Everything except the object
# list and the vote matrix is copied from the P7/P8 arms, so a difference here
# cannot come from rotations, capacity or sensor noise.
defaults:
  - /monty: evidencegraph_exp1000_emin_t3_tot2500
  - /monty/motor_system_config: distant_5
  - /monty/learning_module: polybrains_5lm
  - /monty/sensor_module: 5sm_camera_dist_noise
  - /monty/connectivity: 5lm_5sm
  - /environment: mujoco_dist_agent_sensors5
  - /env_interface: eval_distinctobj_random
  - /env_interface/positioning_procedures_eval: getgoodview_viewfinder_patch0
  - /env_interface/transform: missing_depthto3d_sensor6
  - /logging: basic_warning_monty_runs

polybrains:
  eval_rotations:
{rotations}
  vote_mode: max
  consensus_tau: 0.15
  adaptive_weight: false

experiment:
  _target_: tbp.monty.frameworks.experiments.object_recognition_experiments.MontyObjectRecognitionExperiment
  config:
    show_sensor_output: false
    max_train_steps: 1000
    max_eval_steps: 500
    max_total_steps: 6000
    n_train_epochs: 1
    do_train: false
    do_eval: true
    model_name_or_path: ${{path.expanduser:${{oc.env:MONTY_MODELS}}}}/polybrains/pb_holdout9_5lm/pretrained/
    n_eval_epochs: 1
    match_criterion:
      _target_: tbp.monty.experiment.match_criteria.AnyLMsMatch
      count: 1
    seed: 42{vote}
    eval_env_interface_args:
      object_names:
        - {obj}
      object_init_sampler:
        _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
        rotations: ${{polybrains.eval_rotations}}
    supervised_lm_ids: []
    logging:
      run_name: {name}
      monty_handlers:
        - ${{monty.class:tbp.monty.frameworks.loggers.monty_handlers.BasicCSVStatsHandler}}
'''

NOVOTE_BLOCK = """
    monty_config:
      lm_to_lm_vote_matrix: null"""

ARMS = [
    ("p14_holdout_max", HELD_OUT, "",
     "held-out target, voting ON",
     "The treatment. `%s` is absent from every module's graph memory, so no "
     "module can be correct. Whatever agreement appears here is not about "
     "truth." % HELD_OUT),
    ("p14_holdout_novote", HELD_OUT, NOVOTE_BLOCK,
     "held-out target, voting OFF",
     "The baseline for P14b. Five independent modules choosing among nine "
     "wrong labels should rarely agree. The difference against p14_holdout_max "
     "is the manufactured-consensus effect."),
    ("p14_trained_max", CONTROL_OBJECT, "",
     "REPLICATION CONTROL -- trained target, voting ON",
     "MANDATORY control. `%s` IS in the nine. If accuracy here is not normal "
     "(~97%% any), the nine-object pretraining is broken and every P14 number "
     "is void -- a broken model fails everything and its unanimity would look "
     "like a finding." % CONTROL_OBJECT),
]


def main() -> int:
    written = []

    path = os.path.join(EXP, "p14_pretrain9.yaml")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(PRETRAIN.format(
            held=HELD_OUT,
            objects=yaml_list(TRAINED, 8),
            rotations=rot_list(PRETRAIN_ROTATIONS, 10)))
    written.append(path)

    for name, obj, vote, title, why in ARMS:
        path = os.path.join(EXP, "%s.yaml" % name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(EVAL.format(
                name=name, obj=obj, vote=vote, title=title, why=why,
                rotations=rot_list(EVAL_ROTATIONS, 4)))
        written.append(path)

    for path in written:
        print("wrote %s" % os.path.relpath(path, HERE))
    print("\nheld out: %s | trained: %d objects | control: %s"
          % (HELD_OUT, len(TRAINED), CONTROL_OBJECT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
