#!/usr/bin/env python3
"""Generate P13 near-copy configs: H1 clause 2, the disagreement axis.

H1 clause 2: *the multi-frame advantage scales with how much the modules
DISAGREE during inference, not with how many modules there are.*

Testing the "count" term needs 3-LM and 7-LM systems, which upstream does not
ship (only 1/2/5) and which each need their own pretraining run. Testing the
"disagreement" term does NOT: hold the module count at 5 and vary how much the
sensor patches overlap. That is this experiment, and it is the pre-registered
near-copy control -- under H1, modules that are near-copies of each other should
buy nothing.

Four arms, one variable (patch separation), all reusing `pb_indomain_5lm`:

    p13_sep000   0.000  all five patches at the SAME point -- true near-copies
    p13_sep0025  0.0025 quarter of stock
    p13_sep001   0.01   STOCK. Replication control: must reproduce P7's max arm
    p13_sep004   0.04   4x stock, halfway to P6's failed 0.08

## The failure mode this must avoid, and how

P6 moved this variable the OTHER way (0.01 -> 0.08) and it did not produce
disagreement, it produced ABSENCE: patches left the object and `send_out_vote`
returned None 88% of the time. Silence and dissent look identical in output
statistics and are opposite at the mechanism.

So 0.04 is deliberately below P6's 0.08, and **`send_none`% is a mandatory
reported quantity for every arm**, not an optional diagnostic. An arm whose vote
path went quiet is not evidence about disagreement.

The narrowing direction (0.000, 0.0025) carries the mirror risk: patches that
coincide cannot leave the object, so absence is not the danger there -- the
danger is that "5 modules" becomes "1 module counted five times", which is
exactly what the arm is built to demonstrate.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CFG = ROOT / 'configs'
ENV = CFG / 'environment'
EXP = CFG / 'experiment'

SRC = (ROOT / 'upstream/tbp.monty/src/tbp/monty/conf/environment'
       / 'mujoco_dist_agent_sensors5.yaml')

HEADER = """# @package experiment.config.environment
# P13: sensor patch separation = {sep} (stock is 0.01).
#
# H1 clause 2 says the multi-frame advantage tracks DISAGREEMENT, not module
# count. This arm holds the count at 5 and moves the disagreement axis.
#
# MANDATORY: report send_none% (tools/vote_spy.py) for this arm. P6 moved this
# same variable to 0.08 and produced silence, not disagreement -- 88% of votes
# were None. A number from a quiet vote path means nothing.
"""

ARMS = {'p13_sep000': 0.0, 'p13_sep0025': 0.0025,
        'p13_sep001': 0.01, 'p13_sep004': 0.04}


def make_env(name, sep):
    text = SRC.read_text()
    body = text[text.index('env_init_args:'):]

    # Replace only the four patch offsets, leaving patch_0 (0,0,0), the
    # view_finder and the agent position untouched. The offsets are the only
    # occurrences of a bare 0.01/-0.01 inside a `position:` block.
    def repl(m):
        val = float(m.group(2))
        if abs(abs(val) - 0.01) > 1e-12:
            return m.group(0)          # not a patch offset
        return f'{m.group(1)}{sep if val > 0 else -sep}'

    body = re.sub(r'(\n            - )(-?0\.01)\b', repl, body)
    (ENV / f'{name}.yaml').write_text(HEADER.format(sep=sep) + body)
    return body


def make_exp(name):
    base = (EXP / 'p7_e1_ood_max.yaml').read_text()
    s = base[base.index('defaults:'):]
    s = ('# @package _global_\n'
         f'# P13 near-copy arm: {name}. Generated by tools/make_p13_configs.py.\n'
         '# One variable vs p7_e1_ood_max: sensor patch separation.\n') + s
    old = '  - /environment: mujoco_dist_agent_sensors5\n'
    assert old in s, 'p7 config shape changed'
    s = s.replace(old, f'  - /environment: {name}\n')
    s = s.replace('run_name: p7_e1_ood_max', f'run_name: {name}')
    (EXP / f'{name}.yaml').write_text(s)


for name, sep in ARMS.items():
    body = make_env(name, sep)
    make_exp(name)
    got = re.findall(r'\n            - (-?\d*\.?\d+)\b', body)
    print(f'wrote {name}  (offsets present: '
          f'{sorted({float(g) for g in got if abs(float(g)) < 1})})')
