#!/usr/bin/env python3
"""Generate the P15 configs: FOUR held-out objects.

Pre-registered in `PREDICTIONS.md` before this file was written. Follows
`reports/p14-enull.md`.

**Why four and not one.** P14 held out `dice` and the modules converged on
`golf_ball`. Both are small and round, so a perceptual-similarity explanation
was not excluded. Four objects chosen to differ in shape make a single
similarity story impossible: if all four converge on the SAME label it is a
fixed architectural bias; if each converges on a DIFFERENT neighbour the
modules share a perceptual prior.

**The per-object arms exist because a mean can hide an object at zero.** Each
held-out object gets its own arm rather than one arm evaluating all four, so
the breakdown is structural rather than something the analyser has to
reconstruct.
"""
from __future__ import annotations

import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXP = os.path.join(HERE, "configs", "experiment")

ALL_OBJECTS = [
    "mug", "bowl", "potted_meat_can", "spoon", "strawberry",
    "mustard_bottle", "dice", "golf_ball", "c_lego_duplo", "banana",
]

# Chosen for SHAPE DIVERSITY, per the pre-registration: a cube, a long curve,
# a handled cylinder, a small taper. `dice` is kept so P14 can be replicated
# on the new six-object model rather than merely compared against.
HELD_OUT = ["dice", "banana", "mug", "strawberry"]
TRAINED = [o for o in ALL_OBJECTS if o not in HELD_OUT]

# The control object must be TRAINED, or it controls nothing.
CONTROL_OBJECT = "bowl"

EVAL_ROTATIONS = [[35, 45, 0], [325, 45, 0], [35, 315, 0], [325, 315, 0]]
PRETRAIN_ROTATIONS = [
    [0, 0, 0], [0, 90, 0], [0, 270, 0], [90, 0, 0], [90, 180, 0],
]


def yaml_list(items, indent):
    pad = " " * indent
    return "\n".join("%s- %s" % (pad, i) for i in items)


def rot_list(rots, indent):
    pad = " " * indent
    return "\n".join("%s- [%d, %d, %d]" % (pad, r[0], r[1], r[2]) for r in rots)


PRETRAIN = '''# @package _global_
# P15 PRETRAINING -- SIX objects. Held out: {held}.
#
# Generated by tools/make_p15_configs.py. Pre-registered in PREDICTIONS.md.
#
# Four objects are held out rather than P14's one, so that a single
# perceptual-similarity story cannot explain the convergence.
defaults:
  - /monty: graph_exp500_e3_t3_tot2500
  - /monty/motor_system_config: naive_scan_5
  - /monty/learning_module: displacement_5lm
  - /monty/sensor_module: 5sm_camera
  - /monty/connectivity: 5lm_5sm
  - /environment: mujoco_dist_agent_sensors5
  - /env_interface: train_distinctobj_predefined
  - /env_interface/positioning_procedures_train: getgoodview_viewfinder_patch0
  - /env_interface/transform: missing_depthto3d_sensor6
  - /logging: silent_info_train

experiment:
  _target_: tbp.monty.frameworks.experiments.pretraining_experiments.MontySupervisedObjectPretrainingExperiment
  config:
    show_sensor_output: false
    max_train_steps: 1000
    max_eval_steps: 500
    max_total_steps: 6000
    n_train_epochs: 5
    model_name_or_path: ''
    n_eval_epochs: 1
    match_criterion:
      _target_: tbp.monty.experiment.match_criteria.AnyLMsMatch
      count: 1
    seed: 42
    supervised_lm_ids: all
    train_env_interface_args:
      object_names:
{objects}
      object_init_sampler:
        rotations:
{rotations}
    logging:
      run_name: pb_holdout6_5lm
      output_dir: ${{path.expanduser:${{oc.env:MONTY_MODELS}}/polybrains}}
'''

EVAL = '''# @package _global_
# P15 -- {title}
#
# Generated by tools/make_p15_configs.py. Pre-registered in PREDICTIONS.md.
#
# {why}
#
# Loads the SIX-object model `pb_holdout6_5lm`. Rotations, vote rule, capacity
# and sensor noise are copied from the P7/P8/P14 arms, so a difference cannot
# come from anywhere but the object.
defaults:
  - /monty: evidencegraph_exp1000_emin_t3_tot2500
  - /monty/motor_system_config: distant_5
  - /monty/learning_module: polybrains_5lm
  - /monty/sensor_module: 5sm_camera_dist_noise
  - /monty/connectivity: 5lm_5sm
  - /environment: mujoco_dist_agent_sensors5
  - /env_interface: eval_distinctobj_random
  - /env_interface/positioning_procedures_eval: getgoodview_viewfinder_patch0
  - /env_interface/transform: missing_depthto3d_sensor6
  - /logging: basic_warning_monty_runs

polybrains:
  eval_rotations:
{rotations}
  vote_mode: max
  consensus_tau: 0.15
  adaptive_weight: false

experiment:
  _target_: tbp.monty.frameworks.experiments.object_recognition_experiments.MontyObjectRecognitionExperiment
  config:
    show_sensor_output: false
    max_train_steps: 1000
    max_eval_steps: 500
    max_total_steps: 6000
    n_train_epochs: 1
    do_train: false
    do_eval: true
    model_name_or_path: ${{path.expanduser:${{oc.env:MONTY_MODELS}}}}/polybrains/pb_holdout6_5lm/pretrained/
    n_eval_epochs: 1
    match_criterion:
      _target_: tbp.monty.experiment.match_criteria.AnyLMsMatch
      count: 1
    seed: 42{vote}
    eval_env_interface_args:
      object_names:
        - {obj}
      object_init_sampler:
        _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
        rotations: ${{polybrains.eval_rotations}}
    supervised_lm_ids: []
    logging:
      run_name: {name}
      monty_handlers:
        - ${{monty.class:tbp.monty.frameworks.loggers.monty_handlers.BasicCSVStatsHandler}}
'''

NOVOTE_BLOCK = """
    monty_config:
      lm_to_lm_vote_matrix: null"""


def main() -> int:
    written = []

    path = os.path.join(EXP, "p15_pretrain6.yaml")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(PRETRAIN.format(
            held=", ".join(HELD_OUT),
            objects=yaml_list(TRAINED, 8),
            rotations=rot_list(PRETRAIN_ROTATIONS, 10)))
    written.append(path)

    arms = []
    for obj in HELD_OUT:
        arms.append(("p15_%s_max" % obj, obj, "",
                     "held-out %s, voting ON" % obj,
                     "`%s` is absent from every module's graph memory. Any "
                     "agreement here is not about truth." % obj))
        arms.append(("p15_%s_novote" % obj, obj, NOVOTE_BLOCK,
                     "held-out %s, voting OFF" % obj,
                     "P14's central surprise was that 83%% of no-vote episodes "
                     "were already unanimous. This tests whether that holds "
                     "for `%s` too." % obj))
    arms.append(("p15_trained_max", CONTROL_OBJECT, "",
                 "REPLICATION CONTROL -- trained target",
                 "MANDATORY. `%s` IS in the six. A six-object model may be "
                 "weaker than P14's nine-object one; if this control drops "
                 "materially below 100%%, the P14 comparison is qualified."
                 % CONTROL_OBJECT))

    for name, obj, vote, title, why in arms:
        path = os.path.join(EXP, "%s.yaml" % name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(EVAL.format(
                name=name, obj=obj, vote=vote, title=title, why=why,
                rotations=rot_list(EVAL_ROTATIONS, 4)))
        written.append(path)

    for path in written:
        print("wrote %s" % os.path.relpath(path, HERE))
    print("\nheld out: %s" % ", ".join(HELD_OUT))
    print("trained:  %s" % ", ".join(TRAINED))
    print("control:  %s | %d eval arms" % (CONTROL_OBJECT, len(arms)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
